<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['id' => 'DESC']);
    }

    public function findByCategory(Category $category)
    {
        $query = $this->createQueryBuilder('post')
            ->innerJoin('post.categories', 'categories')
            ->where('categories.id = :category_id')
            ->setParameter('category_id', $category->getId())
            ->getQuery();

        return $query->execute();
    }
}
